### ISSUE TITLE
java.lang.NoSuchFieldError: No field a of type Lcom/google/gson/TypeAdapterFactory; in class Lay; or its superclasses (declaration of 'ay' appears in /data/app/com.adenda.example-1/base.apk)

### ISSUE THREAD

**Issue by PrincePoriya** [adenda/adenda-sample-unlock-widget#1]
i have implement adenda in my app successfully but when i enable proguard.adenda gives an error.as bellow.please give me some solution. i found some class in your sdk which have no any package and error appear in that class. please give me some solution.

Process: com.adenda.example, PID: 14780
                                                                    java.lang.NoSuchFieldError: No field a of type Lcom/google/gson/TypeAdapterFactory; in class Lay; or its superclasses (declaration of 'ay' appears in /data/app/com.adenda.example-1/base.apk)
                                                                        at sdk.adenda.modules.MultiprocessPreferences.a(SourceFile:54)
                                                                        at sdk.adenda.modules.MultiprocessPreferences.onCreate(SourceFile:61)
                                                                        at android.content.ContentProvider.attachInfo(ContentProvider.java:1751)
                                                                        at android.content.ContentProvider.attachInfo(ContentProvider.java:1726)
                                                                        at android.app.ActivityThread.installProvider(ActivityThread.java:5852)
                                                                        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5444)
                                                                        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5383)
                                                                        at android.app.ActivityThread.-wrap2(ActivityThread.java)
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1541)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                        at android.os.Looper.loop(Looper.java:154)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6123)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)

**Comment by fdoumet** [comment]
Looks like you haven't configured Progaurd properly for GSON. These are the typical settings:

```
##---------------Begin: proguard configuration for Gson  ----------
# Gson uses generic type information stored in a class file when working with fields. Proguard
# removes such information by default, so configure it to keep all of it.
-keepattributes Signature

# For using GSON @Expose annotation
-keepattributes *Annotation*

# Gson specific classes
-keep class sun.misc.Unsafe { *; }
#-keep class com.google.gson.stream.** { *; }

# Application classes that will be serialized/deserialized over Gson
-keep class com.google.gson.examples.android.model.** { *; }

##---------------End: proguard configuration for Gson  ----------
```

**Comment by PrincePoriya** [comment]
i have already done.but got same issue
here is my proguard rules.file. and i that issue in adenda sample project  i try to enable proguard in sample project of adenda..but not working.

proguard-pro file as below.


`# To enable ProGuard in your project, edit project.properties
# to define the proguard.config property as described in that file.
#
# Add project specific ProGuard rules here.
# By default, the flags in this file are appended to flags specified
# in ${sdk.dir}/tools/proguard/proguard-android.txt
# You can edit the include path and order by changing the ProGuard
# include property in project.properties.
#
# For more details, see
#   http://developer.android.com/guide/developing/tools/proguard.html

# Add any project specific keep options here:

# If your project uses WebView with JS, uncomment the following
# and specify the fully qualified class name to the JavaScript interface
# class:
#-keepclassmembers class fqcn.of.javascript.interface.for.webview {
#   public *;
#}

##---------------Begin: proguard configuration common for all Android apps ----------
-optimizationpasses 5
-dontusemixedcaseclassnames
-dontskipnonpubliclibraryclasses
-dontskipnonpubliclibraryclassmembers
-dontpreverify
-verbose
-dump class_files.txt
-printseeds seeds.txt
-printusage unused.txt
-printmapping mapping.txt
-optimizations !code/simplification/arithmetic,!field/*,!class/merging/*

-allowaccessmodification
-keepattributes *Annotation*
-renamesourcefileattribute SourceFile
-keepattributes SourceFile,LineNumberTable
-repackageclasses ''

-keep public class * extends android.app.Activity
-keep public class * extends android.app.Application
-keep public class * extends android.app.Service
-keep public class * extends android.content.BroadcastReceiver
-keep public class * extends android.content.ContentProvider
-keep public class * extends android.app.backup.BackupAgentHelper
-keep public class * extends android.preference.Preference
-keep public class com.android.vending.licensing.ILicensingService
-dontnote com.android.vending.licensing.ILicensingService

# Explicitly preserve all serialization members. The Serializable interface
# is only a marker interface, so it wouldn't save them.
-keepclassmembers class * implements java.io.Serializable {
    static final long serialVersionUID;
    private static final java.io.ObjectStreamField[] serialPersistentFields;
    private void writeObject(java.io.ObjectOutputStream);
    private void readObject(java.io.ObjectInputStream);
    java.lang.Object writeReplace();
    java.lang.Object readResolve();
}

# Preserve all native method names and the names of their classes.
-keepclasseswithmembernames class * {
    native <methods>;
}

-keepclasseswithmembernames class * {
    public <init>(android.content.Context, android.util.AttributeSet);
}

-keepclasseswithmembernames class * {
    public <init>(android.content.Context, android.util.AttributeSet, int);
}

# Preserve static fields of inner classes of R classes that might be accessed
# through introspection.
-keepclassmembers class **.R$* {
  public static <fields>;
}

# Preserve the special static methods that are required in all enumeration classes.
-keepclassmembers enum * {
    public static **[] values();
    public static ** valueOf(java.lang.String);
}

-keep public class * {
    public protected *;
}

-keep class * implements android.os.Parcelable {
  public static final android.os.Parcelable$Creator *;
}
##---------------End: proguard configuration common for all Android apps ----------

##---------------Begin: proguard configuration for Gson  ----------
# Gson uses generic type information stored in a class file when working with fields. Proguard
# removes such information by default, so configure it to keep all of it.
-keepattributes Signature

# For using GSON @Expose annotation
-keepattributes *Annotation*

# Gson specific classes
-keep class sun.misc.Unsafe { *; }
#-keep class com.google.gson.stream.** { *; }

# Application classes that will be serialized/deserialized over Gson
-keep class com.google.gson.examples.android.model.** { *; }

##---------------End: proguard configuration for Gson  ----------

##---------------Begin: proguard configuration for Adenda  ----------
# -keep class de.greenrobot.** { *; }
 -keep class sdk.adenda.** { *; }
##---------------End: proguard configuration for Adenda  ----------

##---------------Begin: proguard configuration for LockFeed  ----------
# For Flurry content
-keep class com.flurry.** { *; }
-dontwarn com.flurry.**

-keep class com.google.common.** { *; }
-dontwarn com.google.common.**

# For URX
-keep class com.jayway.jsonpath.** { *; }
-dontwarn com.jayway.jsonpath.**

# For App Install Tracking
-keep class com.facebook.** { *;}

# For Javascript execution in Bleacher Report lock screen browser
-keepclassmembers class fqcn.of.javascript.interface.for.webview { public *;}
##---------------End: proguard configuration for LockFeed  ----------

#-keep class com.urbanairship.**{*;}
-dontwarn com.urbanairship.**
`

**Comment by fdoumet** [comment]
The Adenda Example is running Progaurd properly. Something is likely wrong with your setup. Please email `support@adendamedia.com` and include your Adenda username so we may help you offline.

**Comment by PrincePoriya** [comment]
i try all things but getting error.can you share any proguard enabled adenda sample project.? i already  email to adenda support  team.
